storage_path: sqlite:///optuna.db
work_dir: autotune
tools_dir: tools
base_pahcer_file: pahcer_config.toml
optuna_config_path: optuna_config.yaml
case_num_per_group: 10
optuna_study_prefix: study0
input_fn: |
  use proconio::input;
  input! { n: usize, m: usize }
  if n < 100 && m < 100 {
    "0".to_string()
  } else {
    "1".to_string()
  }
