base_dir: ./.autotune
optuna_config_path: autotune_config.yaml
timeout: 600
num_total_seed: 50
case_num_per_group: 10
input_params:
  - name: n
    type: int
    rust_type: usize
    parser:
      type: constant
      index: 0
    partitions: [1, 50, 101]
  - name: m
    type: int
    rust_type: usize
    parser:
      type: constant
      index: 1
    partitions: [1, 50, 101]
optuna:
  settings:
    storage_path: optuna.db
    direction: maximize
    score_type: relative
  pruner:
    threshold: 0.02
  params:
    - name: n_coef
      type: float
      rust_type: f64
      default: 5.0
      min: 1.0
      max: 10.0
    - name: m_coef
      type: float
      rust_type: f64
      default: 5.0
      min: 1.0
      max: 10.0
  ignore_params: []
