[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
ac-library-rs = "0.2.0"
ahc-library = { version = "0.1.0", path = "../../ahc-library" }
fixedbitset = "0.5.7"
itertools = "0.14.0"
num-traits = "0.2.19"
proconio = { version = "0.5", features = ["derive"] }
rand = "0.8"
rand_pcg = "0.9.0"
rustc-hash = "2.1.1"
