settings:
  direction: maximize
  timeout: 600
  score_type: relative
  pruner:
    threshold: 0.02
params:
  - name: START_TEMP
    type: float
    default: 10.0
    min: 1.0
    max: 10000.0
  - name: END_TEMP
    type: float
    default: 1e-1
    min: 1e-3
    max: 1e1
