basedir: .autotune
timeout: 30
num_sample: 1000
input_params:
  - name: N
    type: int
    rust_type: usize
    min: 49
    max: 71
    parser:
      type: constant
      params:
        index: 0
    partitions: [49, 60, 71]
optuna:
  settings:
    storage_path: optuna.db
    direction: maximize
    score_type: absolute
  pruner:
    threshold: 0.02
  params:
    - name: START_TEMP
      type: float
      rust_type: f64
      default: 100.0
      min: 1.0
      max: 1000.0
    - name: END_TEMP
      type: float
      rust_type: f64
      default: 0.01
      min: 0.001
      max: 0.9
  ignore_params:
    - COOLING_RATE
