[project]
name = "ahc-utils"
version = "0.1.0"
description = "A tool to optimize parameters using pahcer and optuna."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.1",
    "classopt>=0.2.1",
    "optuna>=4.2.1",
    "scipy>=1.11.4",
    "types-pyyaml>=6.0.12.20250915",
    "pydantic>=2.11.9",
    "polars>=1.38.1",
]

[project.scripts]
generate-impl = "ahc_utils.generate_impl:main"
pahcer-optuna = "ahc_utils.pahcer_optuna:main"
expander = "ahc_utils.expander:main"
autotune = "ahc_utils.autotune:main"
list = "ahc_utils.list:main"

[tool.uv]
package = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]

 [tool.hatch.build.targets.wheel]
packages = ["src/ahc_utils"]

