work_dir: autotune
tools_dir: tools
base_pahcer_file: pahcer_config.toml
optuna_config_path: optuna_config.yaml
case_num_per_group: 10
optuna_study_prefix: study0
input_fn: |
  use proconio::input;
  input! { n: usize, m: usize }
  if n < 50 && m < 50 {
      "0".to_string()
  } else if n < 101 && m < 50 {
      "1".to_string()
  } else if n < 50 && m < 101 {
      "2".to_string()
  } else {
      "3".to_string()
  }
